module.exports = {
  STORE_KEY: 'a56z0fzrNpl^2',
  BASE_URL: 'http://139.59.76.223/monotech/webservice/',
  Signin :'Signin',
  Signup :'Signup',
  front_main :'front_main',
  industry :'',
  category : '',
   productid :'',
   profile :'',
   name :'',
   email :'',
   mobile :'',
   rating_product : 'rating_product',
   forget_password : 'forget_password',
   update_profile_patient : 'update_profile_patient',
  derive_detail_industry :'derive_detail_industry',
  derive_detail_category : 'derive_detail_category',
  info_number :'',
  userid :'',
  rating :'',
  info_email : '',
  add_bookmark :'add_bookmark',
  list_bookmark: 'list_bookmark',
  mainid : '',
  dervie_detail_of_product : 'dervie_detail_of_product',
  submit_enquiry :'submit_enquiry',
  need_help:'need_help',
  list_enquiry :'list_enquiry',
  submit_consumable_request :'submit_consumable_request',
  COLOR: {
    ORANGE: '#C50',
    DARKBLUE: '#0F3274',
    LIGHTBLUE: '#6EA8DA',
    DARKGRAY: '#999',
  },
};